/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description 用户登录
     *
     *     - **username**: 用户名/工号
     *     - **password**: 密码
     *     - **auth_type**: 认证类型(local/ldap)，留空自动判断
     */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh Token
     * @description 刷新访问Token
     */
    post: operations['refresh_token_api_v1_auth_refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Me
     * @description 获取当前登录用户信息
     */
    get: operations['get_me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description 用户登出（前端清除Token即可）
     */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/password/change': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Change Password
     * @description 修改密码（仅本地认证用户可用）
     */
    post: operations['change_password_api_v1_auth_password_change_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Users
     * @description 获取用户列表（管理员）
     */
    get: operations['list_users_api_v1_users_get']
    put?: never
    /**
     * Create User
     * @description 创建用户（管理员）
     */
    post: operations['create_user_api_v1_users_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get User
     * @description 获取用户详情
     */
    get: operations['get_user_api_v1_users__user_id__get']
    /**
     * Update User
     * @description 更新用户信息
     */
    put: operations['update_user_api_v1_users__user_id__put']
    post?: never
    /**
     * Delete User
     * @description 删除用户（软删除）
     */
    delete: operations['delete_user_api_v1_users__user_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{user_id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update User Status
     * @description 更新用户状态
     */
    put: operations['update_user_status_api_v1_users__user_id__status_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chat/completions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Chat Completion
     * @description 智能问答（非流式）
     *
     *     - **message**: 用户问题
     *     - **session_id**: 会话ID，为空则新建会话
     *     - **kb_ids**: 指定知识库ID列表
     *
     *     返回中含 **message_id**（assistant 回答的ID）与 **session_id**，
     *     前端可用 message_id 对该回答提交反馈。
     */
    post: operations['chat_completion_api_v1_chat_completions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chat/completions/stream': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Chat Completion Stream
     * @description 智能问答（流式）
     *     使用SSE格式返回
     *
     *     注：流式接口暂不落库消息，前端反馈需用非流式接口返回的 message_id。
     */
    post: operations['chat_completion_stream_api_v1_chat_completions_stream_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chat/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Sessions
     * @description 获取用户会话列表
     */
    get: operations['list_sessions_api_v1_chat_sessions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chat/sessions/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Session
     * @description 删除会话（软删，含其消息）
     */
    delete: operations['delete_session_api_v1_chat_sessions__session_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chat/feedback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit Feedback
     * @description 提交消息反馈（点赞/点踩 + 文字反馈）
     */
    post: operations['submit_feedback_api_v1_chat_feedback_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/knowledge/bases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Knowledge Bases
     * @description 获取知识库列表
     */
    get: operations['list_knowledge_bases_api_v1_knowledge_bases_get']
    put?: never
    /**
     * Create Knowledge Base
     * @description 创建知识库
     */
    post: operations['create_knowledge_base_api_v1_knowledge_bases_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/knowledge/bases/{kb_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Knowledge Base
     * @description 获取知识库详情
     */
    get: operations['get_knowledge_base_api_v1_knowledge_bases__kb_id__get']
    /**
     * Update Knowledge Base
     * @description 更新知识库
     */
    put: operations['update_knowledge_base_api_v1_knowledge_bases__kb_id__put']
    post?: never
    /**
     * Delete Knowledge Base
     * @description 删除知识库
     */
    delete: operations['delete_knowledge_base_api_v1_knowledge_bases__kb_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Documents
     * @description 获取文档列表
     */
    get: operations['list_documents_api_v1_documents_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload Document
     * @description 上传文档到知识库
     */
    post: operations['upload_document_api_v1_documents_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/{doc_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Document
     * @description 获取文档详情
     */
    get: operations['get_document_api_v1_documents__doc_id__get']
    put?: never
    post?: never
    /**
     * Delete Document
     * @description 删除文档
     */
    delete: operations['delete_document_api_v1_documents__doc_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/{doc_id}/reindex': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Reindex Document
     * @description 重新索引文档
     */
    post: operations['reindex_document_api_v1_documents__doc_id__reindex_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 列出模板
     * @description 列出所有模板
     */
    get: operations['list_templates_api_v1_models_templates_get']
    put?: never
    /**
     * 创建模板
     * @description 创建预设模板
     */
    post: operations['create_template_api_v1_models_templates_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/templates/{template_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取模板详情
     * @description 获取模板详情
     */
    get: operations['get_template_api_v1_models_templates__template_id__get']
    /**
     * 更新模板
     * @description 更新模板
     */
    put: operations['update_template_api_v1_models_templates__template_id__put']
    post?: never
    /**
     * 删除模板
     * @description 删除模板
     */
    delete: operations['delete_template_api_v1_models_templates__template_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 列出 API Keys
     * @description 列出所有 API Key 元信息（不含明文）
     */
    get: operations['list_api_keys_api_v1_models_keys_get']
    put?: never
    /**
     * 创建 API Key
     * @description 创建新的 API Key
     *
     *     - Key 会加密存储到 Vault
     *     - 返回明文 Key（仅此次可见，请妥善保存）
     *     - 需要管理员权限
     */
    post: operations['create_api_key_api_v1_models_keys_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/keys/{key_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取 API Key 详情
     * @description 获取 API Key 详情（不含明文）
     */
    get: operations['get_api_key_api_v1_models_keys__key_id__get']
    /**
     * 更新 API Key
     * @description 更新 API Key
     *
     *     - 可更新名称、状态、过期时间
     *     - 如提供新 Key，会重新加密存储
     */
    put: operations['update_api_key_api_v1_models_keys__key_id__put']
    post?: never
    /**
     * 删除 API Key
     * @description 删除 API Key（包括 Vault 中的加密数据）
     */
    delete: operations['delete_api_key_api_v1_models_keys__key_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/keys/{key_id}/rotate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 轮换 API Key
     * @description 轮换 API Key
     *
     *     - 生成新的 Key
     *     - 旧 Key 失效
     *     - 返回新明文 Key（仅此次可见）
     */
    post: operations['rotate_api_key_api_v1_models_keys__key_id__rotate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/vault/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Vault 健康检查
     * @description 检查 Vault 服务健康状态
     */
    get: operations['check_vault_health_api_v1_models_vault_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 列出模型实例
     * @description 列出所有模型实例
     */
    get: operations['list_model_instances_api_v1_models_get']
    put?: never
    /**
     * 创建模型实例
     * @description 创建新的模型实例
     *
     *     - 需要关联 API Key（用于调用模型 API）
     *     - 配置包括模型名称、温度、超时等参数
     */
    post: operations['create_model_instance_api_v1_models_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/{model_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取模型实例详情
     * @description 获取模型实例详情
     */
    get: operations['get_model_instance_api_v1_models__model_id__get']
    /**
     * 更新模型实例
     * @description 更新模型实例配置
     *
     *     - 可更新配置参数、API Key 关联
     *     - 更新后自动刷新缓存
     */
    put: operations['update_model_instance_api_v1_models__model_id__put']
    post?: never
    /**
     * 删除模型实例
     * @description 删除模型实例
     */
    delete: operations['delete_model_instance_api_v1_models__model_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/{model_id}/toggle': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 切换模型状态
     * @description 启用/禁用模型
     *
     *     - 禁用后该模型不会被调度使用
     */
    post: operations['toggle_model_status_api_v1_models__model_id__toggle_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/models/compare': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 模型对比
     * @description 对比多个模型的回答效果
     *
     *     - 输入同一问题，返回各模型的回答
     *     - 包含响应时间、Token 消耗等指标
     */
    post: operations['compare_models_api_v1_models_compare_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取模型健康状态
     * @description 获取所有模型健康状态
     *
     *     需要管理员权限
     */
    get: operations['get_models_health_api_v1_health_models_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/models/{model_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取单个模型健康状态
     * @description 获取单个模型健康状态
     *
     *     需要管理员权限
     */
    get: operations['get_model_health_api_v1_health_models__model_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取健康检查摘要
     * @description 获取健康检查摘要统计
     *
     *     需要管理员权限
     */
    get: operations['get_health_summary_api_v1_health_summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stats/usage': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取用量统计
     * @description 获取用量统计
     *
     *     需要管理员权限
     */
    get: operations['get_usage_stats_api_v1_stats_usage_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stats/models/ranking': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取模型排行
     * @description 获取模型使用排行
     *
     *     需要管理员权限
     */
    get: operations['get_model_ranking_api_v1_stats_models_ranking_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stats/users/ranking': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 获取用户排行
     * @description 获取用户使用排行
     *
     *     需要管理员权限
     */
    get: operations['get_user_ranking_api_v1_stats_users_ranking_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/announcements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Announcements
     * @description 获取公告列表（管理员）
     */
    get: operations['list_announcements_api_v1_announcements_get']
    put?: never
    /**
     * Create Announcement
     * @description 创建公告（管理员）
     */
    post: operations['create_announcement_api_v1_announcements_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/announcements/{announcement_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Announcement
     * @description 获取公告详情（管理员）
     */
    get: operations['get_announcement_api_v1_announcements__announcement_id__get']
    /**
     * Update Announcement
     * @description 更新公告（管理员）
     */
    put: operations['update_announcement_api_v1_announcements__announcement_id__put']
    post?: never
    /**
     * Delete Announcement
     * @description 删除公告（管理员，软删）
     */
    delete: operations['delete_announcement_api_v1_announcements__announcement_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/announcements/{announcement_id}/publish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Publish Announcement
     * @description 发布公告（管理员）
     */
    put: operations['publish_announcement_api_v1_announcements__announcement_id__publish_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description 健康检查接口
     */
    get: operations['health_check_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Root
     * @description 根路径
     */
    get: operations['root__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AnnouncementCreate
     * @description 创建公告
     */
    AnnouncementCreate: {
      /**
       * Title
       * @description 公告标题
       */
      title: string
      /**
       * Content
       * @description 公告正文
       */
      content: string
      /**
       * @description 公告类型
       * @default notice
       */
      type: components['schemas']['AnnouncementType']
      /**
       * Pinned
       * @description 是否置顶
       * @default false
       */
      pinned: boolean
    }
    /**
     * AnnouncementListResponse
     * @description 公告列表响应
     */
    AnnouncementListResponse: {
      /** Items */
      items: components['schemas']['AnnouncementResponse'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Page Size */
      page_size: number
    }
    /**
     * AnnouncementResponse
     * @description 公告响应
     */
    AnnouncementResponse: {
      /** Id */
      id: string
      /** Title */
      title: string
      /** Content */
      content: string
      type: components['schemas']['AnnouncementType']
      status: components['schemas']['AnnouncementStatus']
      /** Pinned */
      pinned: boolean
      /** Published At */
      published_at?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * AnnouncementStatus
     * @description 公告状态
     * @enum {string}
     */
    AnnouncementStatus: 'draft' | 'published' | 'archived'
    /**
     * AnnouncementType
     * @description 公告类型
     * @enum {string}
     */
    AnnouncementType: 'notice' | 'maintenance' | 'update'
    /**
     * AnnouncementUpdate
     * @description 更新公告
     */
    AnnouncementUpdate: {
      /** Title */
      title?: string | null
      /** Content */
      content?: string | null
      type?: components['schemas']['AnnouncementType'] | null
      status?: components['schemas']['AnnouncementStatus'] | null
      /** Pinned */
      pinned?: boolean | null
    }
    /**
     * ApiKeyCreate
     * @description 创建 API Key 请求
     */
    ApiKeyCreate: {
      /**
       * Name
       * @description Key 名称
       */
      name: string
      /**
       * Provider
       * @description 提供商名称
       */
      provider: string
      /**
       * Api Key
       * @description API Key 明文（会被加密存储）
       */
      api_key: string
      /**
       * @description 用途
       * @default llm
       */
      usage: components['schemas']['KeyUsage']
      /**
       * Expires At
       * @description 过期时间
       */
      expires_at?: string | null
      /**
       * Description
       * @description 描述
       */
      description?: string | null
    }
    /**
     * ApiKeyCreateResponse
     * @description 创建 API Key 响应（首次显示明文）
     */
    ApiKeyCreateResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Provider */
      provider: string
      /**
       * Api Key
       * @description 明文 Key，仅在创建时返回
       */
      api_key: string
      /** Key Preview */
      key_preview: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * ApiKeyResponse
     * @description API Key 响应（不含明文）
     */
    ApiKeyResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Provider */
      provider: string
      usage: components['schemas']['KeyUsage']
      status: components['schemas']['KeyStatus']
      /**
       * Key Preview
       * @description Key 预览（显示前后各2位）
       */
      key_preview: string
      /** Expires At */
      expires_at: string | null
      /** Description */
      description: string | null
      /** Created By */
      created_by: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * ApiKeyUpdate
     * @description 更新 API Key 请求
     */
    ApiKeyUpdate: {
      /** Name */
      name?: string | null
      /**
       * Api Key
       * @description 新 Key（会重新加密存储）
       */
      api_key?: string | null
      status?: components['schemas']['KeyStatus'] | null
      /** Expires At */
      expires_at?: string | null
      /** Description */
      description?: string | null
    }
    /** Body_upload_document_api_v1_documents_upload_post */
    Body_upload_document_api_v1_documents_upload_post: {
      /**
       * File
       * Format: binary
       */
      file: string
    }
    /**
     * ChangePasswordRequest
     * @description 修改密码请求
     */
    ChangePasswordRequest: {
      /** Old Password */
      old_password: string
      /** New Password */
      new_password: string
    }
    /**
     * ChatFeedbackRequest
     * @description 聊天反馈请求
     */
    ChatFeedbackRequest: {
      /** Message Id */
      message_id: string
      /** Is Liked */
      is_liked: boolean
      /** Feedback */
      feedback?: string | null
    }
    /**
     * ChatRequest
     * @description 聊天请求
     */
    ChatRequest: {
      /**
       * Message
       * @description 用户消息
       */
      message: string
      /**
       * Session Id
       * @description 会话ID(为空则新建)
       */
      session_id?: string | null
      /**
       * Kb Ids
       * @description 指定知识库
       */
      kb_ids?: string[] | null
      /**
       * Stream
       * @description 是否流式输出
       * @default true
       */
      stream: boolean
    }
    /**
     * DataResponse
     * @description 带数据的响应
     */
    DataResponse: {
      /**
       * Code
       * @default SUCCESS
       */
      code: string
      /**
       * Message
       * @default 操作成功
       */
      message: string
      /** Data */
      data?: unknown
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthCheckSummary
     * @description 健康检查摘要
     */
    HealthCheckSummary: {
      /** Total Models */
      total_models: number
      /** Healthy Count */
      healthy_count: number
      /** Degraded Count */
      degraded_count: number
      /** Unhealthy Count */
      unhealthy_count: number
      /** Unknown Count */
      unknown_count: number
    }
    /**
     * HealthStatusResponse
     * @description 健康状态响应
     */
    HealthStatusResponse: {
      /** Model Id */
      model_id: string
      /** Status */
      status: string
      /** Latency Ms */
      latency_ms?: number | null
      /** Error Message */
      error_message?: string | null
      /** Checked At */
      checked_at?: string | null
    }
    /**
     * KeyStatus
     * @description Key 状态
     * @enum {string}
     */
    KeyStatus: 'active' | 'inactive' | 'expired'
    /**
     * KeyUsage
     * @description Key 用途
     * @enum {string}
     */
    KeyUsage: 'llm' | 'embedding' | 'both'
    /**
     * KnowledgeBaseCreate
     * @description 创建知识库
     */
    KnowledgeBaseCreate: {
      /** Name */
      name: string
      /** Description */
      description?: string | null
    }
    /**
     * KnowledgeBaseUpdate
     * @description 更新知识库
     */
    KnowledgeBaseUpdate: {
      /** Name */
      name?: string | null
      /** Description */
      description?: string | null
    }
    /**
     * ListResponse
     * @description 列表响应
     */
    ListResponse: {
      /**
       * Code
       * @default SUCCESS
       */
      code: string
      /**
       * Message
       * @default 操作成功
       */
      message: string
      /**
       * Data
       * @default []
       */
      data: unknown[]
      /**
       * Total
       * @default 0
       */
      total: number
      /**
       * Page
       * @default 1
       */
      page: number
      /**
       * Page Size
       * @default 20
       */
      page_size: number
    }
    /**
     * LoginRequest
     * @description 登录请求
     */
    LoginRequest: {
      /**
       * Username
       * @description 用户名/工号
       */
      username: string
      /**
       * Password
       * @description 密码
       */
      password: string
      /**
       * Auth Type
       * @description 认证类型: local/ldap
       */
      auth_type?: string | null
    }
    /**
     * ModelCompareRequest
     * @description 模型对比请求
     */
    ModelCompareRequest: {
      /**
       * Question
       * @description 测试问题
       */
      question: string
      /**
       * Model Ids
       * @description 要对比的模型 ID
       */
      model_ids: string[]
    }
    /**
     * ModelCompareResponse
     * @description 模型对比响应
     */
    ModelCompareResponse: {
      /** Question */
      question: string
      /** Results */
      results: components['schemas']['ModelCompareResult'][]
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string
    }
    /**
     * ModelCompareResult
     * @description 单个模型对比结果
     */
    ModelCompareResult: {
      /** Model Id */
      model_id: string
      /** Model Name */
      model_name: string
      /** Response */
      response: string
      /** Latency Ms */
      latency_ms: number
      /** Input Tokens */
      input_tokens: number
      /** Output Tokens */
      output_tokens: number
      /** Success */
      success: boolean
      /** Error */
      error?: string | null
    }
    /**
     * ModelConfig
     * @description 模型配置
     */
    ModelConfig: {
      /**
       * Model
       * @description 模型名称
       */
      model: string
      /**
       * Api Base
       * @description API 基础地址
       */
      api_base?: string | null
      /**
       * Temperature
       * @description 温度参数
       * @default 0.7
       */
      temperature: number
      /**
       * Max Tokens
       * @description 最大 Token 数
       * @default 2048
       */
      max_tokens: number
      /**
       * Top P
       * @description Top P 参数
       */
      top_p?: number | null
      /**
       * Timeout
       * @description 超时时间（秒）
       * @default 60
       */
      timeout: number
    }
    /**
     * ModelInstanceCreate
     * @description 创建模型实例请求
     */
    ModelInstanceCreate: {
      /**
       * Name
       * @description 实例名称
       */
      name: string
      /** @description 提供商 */
      provider: components['schemas']['ModelProvider']
      /**
       * Api Key Id
       * @description 关联的 API Key ID
       */
      api_key_id?: string | null
      /**
       * Model Type
       * @description 模型类型: chat/embedding
       * @default chat
       */
      model_type: string
      config: components['schemas']['ModelConfig']
      /** Description */
      description?: string | null
    }
    /**
     * ModelInstanceListResponse
     * @description 模型实例列表响应
     */
    ModelInstanceListResponse: {
      /** Items */
      items: components['schemas']['ModelInstanceResponse'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Page Size */
      page_size: number
    }
    /**
     * ModelInstanceResponse
     * @description 模型实例响应
     */
    ModelInstanceResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      provider: components['schemas']['ModelProvider']
      /** Api Key Id */
      api_key_id: string | null
      /** Model Type */
      model_type: string
      config: components['schemas']['ModelConfig']
      status: components['schemas']['ModelStatus']
      /** Description */
      description: string | null
      /** Created By */
      created_by: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * ModelInstanceUpdate
     * @description 更新模型实例请求
     */
    ModelInstanceUpdate: {
      /** Name */
      name?: string | null
      /** Api Key Id */
      api_key_id?: string | null
      status?: components['schemas']['ModelStatus'] | null
      config?: components['schemas']['ModelConfig'] | null
      /** Description */
      description?: string | null
    }
    /**
     * ModelProvider
     * @description 模型提供商
     * @enum {string}
     */
    ModelProvider: 'openai' | 'anthropic' | 'qwen' | 'doubao' | 'local' | 'other'
    /**
     * ModelStatus
     * @description 模型状态
     * @enum {string}
     */
    ModelStatus: 'active' | 'inactive' | 'maintenance'
    /**
     * RankingItem
     * @description 排行项
     */
    RankingItem: {
      /** Model Id */
      model_id?: string | null
      /** User Id */
      user_id?: string | null
      /** Total Tokens */
      total_tokens: number
      /** Total Cost */
      total_cost: number
      /** Total Calls */
      total_calls: number
    }
    /**
     * RankingResponse
     * @description 排行响应
     */
    RankingResponse: {
      /** Items */
      items: components['schemas']['RankingItem'][]
    }
    /**
     * RefreshTokenRequest
     * @description 刷新Token请求
     */
    RefreshTokenRequest: {
      /** Refresh Token */
      refresh_token: string
    }
    /**
     * ResponseBase
     * @description 基础响应
     */
    ResponseBase: {
      /**
       * Code
       * @default SUCCESS
       */
      code: string
      /**
       * Message
       * @default 操作成功
       */
      message: string
    }
    /**
     * TemplateCreate
     * @description 创建模板请求
     */
    TemplateCreate: {
      /** Name */
      name: string
      /** Template Type */
      template_type: string
      /** Template */
      template: Record<string, never>
      /** Description */
      description?: string | null
      /**
       * Is Default
       * @default false
       */
      is_default: boolean
      /** Tags */
      tags?: string[] | null
      /** Category */
      category?: string | null
    }
    /**
     * TemplateListResponse
     * @description 模板列表响应
     */
    TemplateListResponse: {
      /** Items */
      items: components['schemas']['TemplateResponse'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Page Size */
      page_size: number
    }
    /**
     * TemplateResponse
     * @description 模板响应
     */
    TemplateResponse: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Template Type */
      template_type: string
      /** Description */
      description: string | null
      /** Template */
      template: Record<string, never>
      /** Is Default */
      is_default: boolean
      /** Is Active */
      is_active: boolean
      /** Tags */
      tags: string[]
      /** Category */
      category: string | null
      /** Version */
      version: string
      /** Created By */
      created_by: string | null
      /** Created At */
      created_at: string
    }
    /**
     * TemplateUpdate
     * @description 更新模板请求
     */
    TemplateUpdate: {
      /** Name */
      name?: string | null
      /** Template */
      template?: Record<string, never> | null
      /** Description */
      description?: string | null
      /** Is Default */
      is_default?: boolean | null
      /** Is Active */
      is_active?: boolean | null
      /** Tags */
      tags?: string[] | null
      /** Category */
      category?: string | null
    }
    /**
     * UsageStatsResponse
     * @description 用量统计响应
     */
    UsageStatsResponse: {
      /** Total Tokens */
      total_tokens: number
      /** Input Tokens */
      input_tokens: number
      /** Output Tokens */
      output_tokens: number
      /** Total Cost */
      total_cost: number
      /** Total Calls */
      total_calls: number
      /** Success Calls */
      success_calls: number
      /** Failed Calls */
      failed_calls: number
    }
    /**
     * UserCreate
     * @description 创建用户
     */
    UserCreate: {
      /** Username */
      username: string
      /** Email */
      email?: string | null
      /** Phone */
      phone?: string | null
      /** Display Name */
      display_name?: string | null
      /** Avatar */
      avatar?: string | null
      /**
       * Role
       * @default staff
       */
      role: string
      /** Department */
      department?: string | null
      /** Position */
      position?: string | null
      /** Password */
      password: string
      /**
       * Auth Type
       * @default local
       */
      auth_type: string
    }
    /**
     * UserUpdate
     * @description 更新用户
     */
    UserUpdate: {
      /** Email */
      email?: string | null
      /** Phone */
      phone?: string | null
      /** Display Name */
      display_name?: string | null
      /** Avatar */
      avatar?: string | null
      /** Department */
      department?: string | null
      /** Position */
      position?: string | null
      /** Status */
      status?: string | null
      /** Description */
      description?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  refresh_token_api_v1_auth_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
    }
  }
  change_password_api_v1_auth_password_change_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_user_api_v1_users_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_user_api_v1_users__user_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_user_api_v1_users__user_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_user_api_v1_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_user_status_api_v1_users__user_id__status_put: {
    parameters: {
      query: {
        status: string
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  chat_completion_api_v1_chat_completions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  chat_completion_stream_api_v1_chat_completions_stream_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_sessions_api_v1_chat_sessions_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListResponse']
        }
      }
    }
  }
  delete_session_api_v1_chat_sessions__session_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_feedback_api_v1_chat_feedback_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatFeedbackRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_knowledge_bases_api_v1_knowledge_bases_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_knowledge_base_api_v1_knowledge_bases_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['KnowledgeBaseCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_knowledge_base_api_v1_knowledge_bases__kb_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        kb_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_knowledge_base_api_v1_knowledge_bases__kb_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        kb_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['KnowledgeBaseUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_knowledge_base_api_v1_knowledge_bases__kb_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        kb_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_documents_api_v1_documents_get: {
    parameters: {
      query?: {
        kb_id?: string | null
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_document_api_v1_documents_upload_post: {
    parameters: {
      query: {
        kb_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_document_api_v1_documents_upload_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_document_api_v1_documents__doc_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DataResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_document_api_v1_documents__doc_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reindex_document_api_v1_documents__doc_id__reindex_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        doc_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResponseBase']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_templates_api_v1_models_templates_get: {
    parameters: {
      query?: {
        template_type?: string | null
        category?: string | null
        is_active?: boolean | null
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_template_api_v1_models_templates_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TemplateCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_template_api_v1_models_templates__template_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_template_api_v1_models_templates__template_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TemplateUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_template_api_v1_models_templates__template_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_api_keys_api_v1_models_keys_get: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页数量 */
        page_size?: number
        /** @description 提供商筛选 */
        provider?: string | null
        /** @description 用途筛选 */
        usage?: string | null
        /** @description 状态筛选 */
        status?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_key_api_v1_models_keys_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApiKeyCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_api_key_api_v1_models_keys__key_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        key_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_api_key_api_v1_models_keys__key_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        key_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApiKeyUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_api_key_api_v1_models_keys__key_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        key_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  rotate_api_key_api_v1_models_keys__key_id__rotate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        key_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  check_vault_health_api_v1_models_vault_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  list_model_instances_api_v1_models_get: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页数量 */
        page_size?: number
        /** @description 提供商筛选 */
        provider?: string | null
        /** @description 模型类型筛选 */
        model_type?: string | null
        /** @description 状态筛选 */
        status?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelInstanceListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_model_instance_api_v1_models_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ModelInstanceCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelInstanceResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_model_instance_api_v1_models__model_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelInstanceResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_model_instance_api_v1_models__model_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ModelInstanceUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelInstanceResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_model_instance_api_v1_models__model_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  toggle_model_status_api_v1_models__model_id__toggle_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelInstanceResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  compare_models_api_v1_models_compare_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ModelCompareRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelCompareResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_models_health_api_v1_health_models_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthStatusResponse'][]
        }
      }
    }
  }
  get_model_health_api_v1_health_models__model_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        model_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthStatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_health_summary_api_v1_health_summary_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthCheckSummary']
        }
      }
    }
  }
  get_usage_stats_api_v1_stats_usage_get: {
    parameters: {
      query?: {
        /** @description 模型ID筛选 */
        model_id?: string | null
        /** @description 用户ID筛选 */
        user_id?: string | null
        /** @description 统计天数 */
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsageStatsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_model_ranking_api_v1_stats_models_ranking_get: {
    parameters: {
      query?: {
        /** @description 统计天数 */
        days?: number
        /** @description 返回数量 */
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RankingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_user_ranking_api_v1_stats_users_ranking_get: {
    parameters: {
      query?: {
        /** @description 统计天数 */
        days?: number
        /** @description 返回数量 */
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RankingResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_announcements_api_v1_announcements_get: {
    parameters: {
      query?: {
        status?: components['schemas']['AnnouncementStatus'] | null
        type?: components['schemas']['AnnouncementType'] | null
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnnouncementListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_announcement_api_v1_announcements_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AnnouncementCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnnouncementResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_announcement_api_v1_announcements__announcement_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        announcement_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnnouncementResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_announcement_api_v1_announcements__announcement_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        announcement_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AnnouncementUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnnouncementResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_announcement_api_v1_announcements__announcement_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        announcement_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  publish_announcement_api_v1_announcements__announcement_id__publish_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        announcement_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AnnouncementResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  root__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
