"""add announcement

Revision ID: 8abc1234abcd
Revises: a3936bd6bb9e
Create Date: 2026-08-02 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8abc1234abcd"
down_revision: Union[str, None] = "a3936bd6bb9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column(
            "title", sa.String(length=200), nullable=False, comment="公告标题"
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="公告正文"),
        sa.Column(
            "type",
            sa.Enum("NOTICE", "MAINTENANCE", "UPDATE", name="announcementtype"),
            nullable=False,
            comment="公告类型",
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="announcementstatus"),
            nullable=False,
            comment="公告状态",
        ),
        sa.Column("pinned", sa.Boolean(), nullable=False, comment="是否置顶"),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="发布时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("announcements")
    # ### end Alembic commands ###
