"""initial schema

Revision ID: a3936bd6bb9e
Revises:
Create Date: 2026-08-02 11:00:04.563233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a3936bd6bb9e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_experiments",
        sa.Column("name", sa.String(length=100), nullable=False, comment="实验名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="实验描述"),
        sa.Column(
            "experiment_type", sa.String(length=30), nullable=False, comment="实验类型"
        ),
        sa.Column(
            "target_model_id", sa.String(length=36), nullable=True, comment="目标模型ID"
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="状态"),
        sa.Column(
            "start_at", sa.DateTime(timezone=True), nullable=True, comment="开始时间"
        ),
        sa.Column(
            "end_at", sa.DateTime(timezone=True), nullable=True, comment="结束时间"
        ),
        sa.Column(
            "winner_group_id", sa.String(length=36), nullable=True, comment="获胜分组ID"
        ),
        sa.Column("conclusion", sa.Text(), nullable=True, comment="实验结论"),
        sa.Column("created_by", sa.String(length=36), nullable=True, comment="创建人"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ab_groups",
        sa.Column(
            "experiment_id", sa.String(length=36), nullable=False, comment="实验ID"
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="分组名称"),
        sa.Column(
            "model_id", sa.String(length=36), nullable=True, comment="使用的模型ID"
        ),
        sa.Column("config_snapshot", sa.JSON(), nullable=True, comment="配置快照"),
        sa.Column(
            "traffic_percentage", sa.Integer(), nullable=False, comment="流量分配"
        ),
        sa.Column(
            "skip_on_circuit_open", sa.Boolean(), nullable=False, comment="熔断时跳过"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ab_results",
        sa.Column(
            "experiment_id", sa.String(length=36), nullable=False, comment="实验ID"
        ),
        sa.Column("group_id", sa.String(length=36), nullable=False, comment="分组ID"),
        sa.Column(
            "session_id", sa.String(length=100), nullable=False, comment="会话ID"
        ),
        sa.Column("user_id", sa.String(length=36), nullable=True, comment="用户ID"),
        sa.Column("question", sa.Text(), nullable=False, comment="用户问题"),
        sa.Column("answer", sa.Text(), nullable=True, comment="模型回答"),
        sa.Column(
            "model_id", sa.String(length=36), nullable=True, comment="实际调用的模型ID"
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True, comment="响应时间"),
        sa.Column("input_tokens", sa.Integer(), nullable=True, comment="输入Token数"),
        sa.Column("output_tokens", sa.Integer(), nullable=True, comment="输出Token数"),
        sa.Column("is_success", sa.Boolean(), nullable=False, comment="是否成功"),
        sa.Column(
            "feedback_score", sa.Integer(), nullable=True, comment="用户反馈：1-5"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=100), nullable=False, comment="Key 名称"),
        sa.Column(
            "provider", sa.String(length=50), nullable=False, comment="提供商名称"
        ),
        sa.Column(
            "vault_path",
            sa.String(length=255),
            nullable=False,
            comment="Vault 中 Secret 的路径",
        ),
        sa.Column(
            "key_preview",
            sa.String(length=10),
            nullable=False,
            comment="Key 预览（显示前后各2位）",
        ),
        sa.Column(
            "usage",
            sa.Enum("LLM", "EMBEDDING", "BOTH", name="apikeyusage"),
            nullable=False,
            comment="用途",
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "EXPIRED", name="apikeystatus"),
            nullable=False,
            comment="状态",
        ),
        sa.Column(
            "expires_at", sa.DateTime(timezone=True), nullable=True, comment="过期时间"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="描述"),
        sa.Column(
            "created_by", sa.String(length=36), nullable=True, comment="创建人 ID"
        ),
        sa.Column("use_count", sa.Integer(), nullable=False, comment="使用次数"),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="最后使用时间",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.create_index(
        op.f("ix_api_keys_vault_path"), "api_keys", ["vault_path"], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN",
                "LOGOUT",
                "LOGIN_FAILED",
                "PASSWORD_CHANGED",
                "USER_CREATED",
                "USER_UPDATED",
                "USER_DELETED",
                "USER_DISABLED",
                "MODEL_CREATED",
                "MODEL_UPDATED",
                "MODEL_DELETED",
                "MODEL_ENABLED",
                "MODEL_DISABLED",
                "API_KEY_CREATED",
                "API_KEY_UPDATED",
                "API_KEY_DELETED",
                "API_KEY_ROTATED",
                "CONFIG_UPDATED",
                "KB_CREATED",
                "KB_UPDATED",
                "KB_DELETED",
                "DOCUMENT_UPLOADED",
                "DOCUMENT_DELETED",
                "QUERY_EXECUTED",
                name="auditaction",
            ),
            nullable=False,
            comment="操作类型",
        ),
        sa.Column(
            "level",
            sa.Enum("INFO", "WARNING", "ERROR", "CRITICAL", name="auditlevel"),
            nullable=False,
            comment="日志级别",
        ),
        sa.Column("user_id", sa.String(length=36), nullable=True, comment="操作用户ID"),
        sa.Column(
            "username", sa.String(length=64), nullable=True, comment="操作用户名"
        ),
        sa.Column(
            "user_role", sa.String(length=32), nullable=True, comment="操作用户角色"
        ),
        sa.Column(
            "target_type",
            sa.String(length=50),
            nullable=True,
            comment="目标类型（如: user, model, api_key）",
        ),
        sa.Column("target_id", sa.String(length=36), nullable=True, comment="目标ID"),
        sa.Column(
            "target_name", sa.String(length=100), nullable=True, comment="目标名称"
        ),
        sa.Column("method", sa.String(length=10), nullable=True, comment="HTTP方法"),
        sa.Column("path", sa.String(length=500), nullable=True, comment="请求路径"),
        sa.Column("request_data", sa.Text(), nullable=True, comment="请求数据（脱敏）"),
        sa.Column("response_status", sa.Integer(), nullable=True, comment="响应状态码"),
        sa.Column("success", sa.Boolean(), nullable=False, comment="是否成功"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column(
            "ip_address", sa.String(length=45), nullable=True, comment="客户端IP"
        ),
        sa.Column(
            "user_agent", sa.String(length=500), nullable=True, comment="User-Agent"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="操作时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "circuit_breaker_states",
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="模型ID"),
        sa.Column(
            "state",
            sa.String(length=20),
            nullable=False,
            comment="状态：closed/open/half_open",
        ),
        sa.Column(
            "failure_count", sa.Integer(), nullable=False, comment="连续失败次数"
        ),
        sa.Column(
            "success_count", sa.Integer(), nullable=False, comment="连续成功次数"
        ),
        sa.Column(
            "last_failure_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="最后失败时间",
        ),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="熔断开始时间",
        ),
        sa.Column(
            "closed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="熔断结束时间",
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id"),
    )
    op.create_table(
        "cost_alerts",
        sa.Column(
            "alert_name", sa.String(length=100), nullable=False, comment="告警名称"
        ),
        sa.Column(
            "target_type",
            sa.String(length=20),
            nullable=False,
            comment="目标类型：global/model/user",
        ),
        sa.Column("target_id", sa.String(length=36), nullable=True, comment="目标ID"),
        sa.Column(
            "threshold_type",
            sa.String(length=20),
            nullable=False,
            comment="阈值类型：daily/monthly/total",
        ),
        sa.Column(
            "threshold_value",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="阈值金额",
        ),
        sa.Column("level", sa.String(length=20), nullable=False, comment="告警级别"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="状态"),
        sa.Column(
            "current_value",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="当前金额",
        ),
        sa.Column("message", sa.Text(), nullable=True, comment="告警消息"),
        sa.Column(
            "period_start",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="统计周期开始",
        ),
        sa.Column(
            "period_end",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="统计周期结束",
        ),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="触发时间",
        ),
        sa.Column(
            "resolved_at", sa.DateTime(timezone=True), nullable=True, comment="解决时间"
        ),
        sa.Column("resolved_by", sa.String(length=36), nullable=True, comment="解决人"),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("auto_resolve", sa.Boolean(), nullable=False, comment="是否自动解决"),
        sa.Column("notify_channels", sa.JSON(), nullable=False, comment="通知渠道"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_health_logs",
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="模型ID"),
        sa.Column(
            "check_type",
            sa.String(length=20),
            nullable=False,
            comment="检查类型：quick/full/comprehensive",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="状态：healthy/degraded/unhealthy/unknown",
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True, comment="响应延迟"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column(
            "checked_at", sa.DateTime(timezone=True), nullable=False, comment="检查时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_health_logs_checked_at"),
        "model_health_logs",
        ["checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_health_logs_model_id"),
        "model_health_logs",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_health_logs_status"),
        "model_health_logs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "model_instances",
        sa.Column("name", sa.String(length=100), nullable=False, comment="实例名称"),
        sa.Column(
            "provider",
            sa.Enum(
                "OPENAI",
                "ANTHROPIC",
                "QWEN",
                "DOUBAO",
                "LOCAL",
                "OTHER",
                name="modelprovider",
            ),
            nullable=False,
            comment="提供商",
        ),
        sa.Column(
            "model_type",
            sa.String(length=20),
            nullable=False,
            comment="模型类型: chat/embedding",
        ),
        sa.Column(
            "api_key_id",
            sa.String(length=36),
            nullable=True,
            comment="关联的 API Key ID",
        ),
        sa.Column(
            "config", sa.JSON(), nullable=False, comment="模型配置（温度、超时等）"
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "MAINTENANCE", name="modelstatus"),
            nullable=False,
            comment="状态",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="描述"),
        sa.Column(
            "created_by", sa.String(length=36), nullable=True, comment="创建人 ID"
        ),
        sa.Column("use_count", sa.Integer(), nullable=False, comment="使用次数"),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="最后使用时间",
        ),
        sa.Column(
            "embedding_dimension",
            sa.Integer(),
            nullable=True,
            comment="向量维度（Embedding 模型专用）",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_instances_api_key_id"),
        "model_instances",
        ["api_key_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_instances_status"), "model_instances", ["status"], unique=False
    )
    op.create_table(
        "model_usage_daily",
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="模型ID"),
        sa.Column("date", sa.Date(), nullable=False, comment="统计日期"),
        sa.Column("total_calls", sa.Integer(), nullable=False, comment="总调用次数"),
        sa.Column("success_calls", sa.Integer(), nullable=False, comment="成功次数"),
        sa.Column("failed_calls", sa.Integer(), nullable=False, comment="失败次数"),
        sa.Column(
            "total_input_tokens", sa.Integer(), nullable=False, comment="总输入Token"
        ),
        sa.Column(
            "total_output_tokens", sa.Integer(), nullable=False, comment="总输出Token"
        ),
        sa.Column(
            "avg_latency_ms", sa.Integer(), nullable=False, comment="平均响应时间"
        ),
        sa.Column(
            "success_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            comment="成功率",
        ),
        sa.Column(
            "estimated_cost",
            sa.Numeric(precision=10, scale=4),
            nullable=False,
            comment="预估费用",
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_usage_daily_date"), "model_usage_daily", ["date"], unique=False
    )
    op.create_table(
        "model_usage_logs",
        sa.Column("model_id", sa.String(length=36), nullable=False, comment="模型ID"),
        sa.Column("user_id", sa.String(length=36), nullable=True, comment="用户ID"),
        sa.Column("session_id", sa.String(length=100), nullable=True, comment="会话ID"),
        sa.Column("scene", sa.String(length=50), nullable=True, comment="使用场景"),
        sa.Column("input_tokens", sa.Integer(), nullable=False, comment="输入Token数"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, comment="输出Token数"),
        sa.Column("total_tokens", sa.Integer(), nullable=False, comment="总Token数"),
        sa.Column("latency_ms", sa.Integer(), nullable=True, comment="响应时间"),
        sa.Column("success", sa.Boolean(), nullable=False, comment="是否成功"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column(
            "cost",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="预估费用",
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_usage_logs_created_at"),
        "model_usage_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_usage_logs_model_id"),
        "model_usage_logs",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_usage_logs_user_id"),
        "model_usage_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "model_versions",
        sa.Column(
            "model_id", sa.String(length=36), nullable=False, comment="模型实例ID"
        ),
        sa.Column(
            "version", sa.String(length=50), nullable=False, comment="版本号：v1.0"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="版本说明"),
        sa.Column("config_snapshot", sa.JSON(), nullable=False, comment="完整配置快照"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="状态"),
        sa.Column(
            "rollout_percentage", sa.Integer(), nullable=False, comment="灰度发布百分比"
        ),
        sa.Column("created_by", sa.String(length=36), nullable=True, comment="创建人"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_versions_model_id"), "model_versions", ["model_id"], unique=False
    )
    op.create_table(
        "preset_templates",
        sa.Column("name", sa.String(length=100), nullable=False, comment="模板名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="模板描述"),
        sa.Column(
            "template_type",
            sa.Enum(
                "CHAT",
                "SYSTEM_PROMPT",
                "RAG_QUERY",
                "EMBEDDING",
                "MODEL",
                name="templatetype",
            ),
            nullable=False,
            comment="模板类型",
        ),
        sa.Column(
            "template", sa.JSON(), nullable=False, comment="模板内容（JSON格式）"
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="是否默认模板"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("tags", sa.JSON(), nullable=False, comment="标签"),
        sa.Column("category", sa.String(length=50), nullable=True, comment="分类"),
        sa.Column("version", sa.String(length=20), nullable=False, comment="模板版本"),
        sa.Column(
            "created_by", sa.String(length=36), nullable=True, comment="创建人ID"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_limit_configs",
        sa.Column(
            "limit_type",
            sa.String(length=30),
            nullable=False,
            comment="限流类型：global/user/model",
        ),
        sa.Column(
            "target_id",
            sa.String(length=36),
            nullable=True,
            comment="目标ID（模型ID/用户ID等）",
        ),
        sa.Column("max_requests", sa.Integer(), nullable=False, comment="最大请求数"),
        sa.Column(
            "window_seconds", sa.Integer(), nullable=False, comment="时间窗口（秒）"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_limit_records",
        sa.Column(
            "limit_type", sa.String(length=30), nullable=False, comment="限流类型"
        ),
        sa.Column("target_id", sa.String(length=36), nullable=True, comment="目标ID"),
        sa.Column("request_count", sa.Integer(), nullable=False, comment="本次请求数"),
        sa.Column("limited", sa.Boolean(), nullable=False, comment="是否被限流"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "router_logs",
        sa.Column(
            "session_id", sa.String(length=100), nullable=False, comment="会话ID"
        ),
        sa.Column("user_id", sa.String(length=36), nullable=True, comment="用户ID"),
        sa.Column(
            "question_preview", sa.String(length=200), nullable=True, comment="问题预览"
        ),
        sa.Column(
            "complexity", sa.String(length=20), nullable=True, comment="判定复杂度"
        ),
        sa.Column(
            "routed_model_id",
            sa.String(length=36),
            nullable=True,
            comment="路由到的模型",
        ),
        sa.Column("routing_reason", sa.Text(), nullable=True, comment="路由原因"),
        sa.Column("latency_ms", sa.Integer(), nullable=True, comment="路由决策耗时"),
        sa.Column("is_fallback", sa.Boolean(), nullable=False, comment="是否降级"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "router_policies",
        sa.Column("name", sa.String(length=100), nullable=False, comment="策略名称"),
        sa.Column("strategy", sa.String(length=30), nullable=False, comment="策略类型"),
        sa.Column("fallback_enabled", sa.Boolean(), nullable=False, comment="启用降级"),
        sa.Column(
            "fallback_model_id",
            sa.String(length=36),
            nullable=True,
            comment="降级模型ID",
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="默认策略"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "router_rules",
        sa.Column("name", sa.String(length=100), nullable=False, comment="规则名称"),
        sa.Column(
            "complexity",
            sa.String(length=20),
            nullable=False,
            comment="复杂度：simple/medium/complex",
        ),
        sa.Column("priority", sa.Integer(), nullable=False, comment="优先级"),
        sa.Column(
            "target_model_id",
            sa.String(length=36),
            nullable=False,
            comment="目标模型ID",
        ),
        sa.Column(
            "version_id",
            sa.String(length=36),
            nullable=True,
            comment="指定版本ID（空则使用活跃版本）",
        ),
        sa.Column("config_override", sa.JSON(), nullable=True, comment="配置覆盖"),
        sa.Column("conditions", sa.JSON(), nullable=False, comment="触发条件"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("created_by", sa.String(length=36), nullable=True, comment="创建人"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, comment="更新时间"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "username", sa.String(length=64), nullable=False, comment="用户名/工号"
        ),
        sa.Column("email", sa.String(length=255), nullable=True, comment="邮箱"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="手机号"),
        sa.Column(
            "display_name", sa.String(length=100), nullable=True, comment="显示名称"
        ),
        sa.Column("avatar", sa.String(length=500), nullable=True, comment="头像URL"),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=True,
            comment="密码哈希（本地认证时必填）",
        ),
        sa.Column(
            "auth_type",
            sa.Enum("LOCAL", "LDAP", "SSO", name="userauthtype"),
            nullable=False,
            comment="认证类型",
        ),
        sa.Column("ldap_dn", sa.String(length=500), nullable=True, comment="LDAP DN"),
        sa.Column(
            "role",
            sa.Enum(
                "SUPER_ADMIN", "ADMIN", "OPERATOR", "STAFF", "GUEST", name="userrole"
            ),
            nullable=False,
            comment="角色",
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "LOCKED", "DISABLED", name="userstatus"),
            nullable=False,
            comment="状态",
        ),
        sa.Column("department", sa.String(length=100), nullable=True, comment="部门"),
        sa.Column("position", sa.String(length=100), nullable=True, comment="职位"),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="最后登录时间",
        ),
        sa.Column(
            "last_login_ip", sa.String(length=45), nullable=True, comment="最后登录IP"
        ),
        sa.Column("login_count", sa.Integer(), nullable=False, comment="登录次数"),
        sa.Column(
            "failed_login_count", sa.Integer(), nullable=False, comment="失败登录次数"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="备注"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "version_releases",
        sa.Column("version_id", sa.String(length=36), nullable=False, comment="版本ID"),
        sa.Column(
            "release_type", sa.String(length=20), nullable=False, comment="发布类型"
        ),
        sa.Column(
            "from_percentage", sa.Integer(), nullable=True, comment="发布前百分比"
        ),
        sa.Column("to_percentage", sa.Integer(), nullable=True, comment="发布后百分比"),
        sa.Column("released_by", sa.String(length=36), nullable=True, comment="发布人"),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="发布时间",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="发布备注"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("version_releases")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("router_rules")
    op.drop_table("router_policies")
    op.drop_table("router_logs")
    op.drop_table("rate_limit_records")
    op.drop_table("rate_limit_configs")
    op.drop_table("preset_templates")
    op.drop_index(op.f("ix_model_versions_model_id"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_model_usage_logs_user_id"), table_name="model_usage_logs")
    op.drop_index(op.f("ix_model_usage_logs_model_id"), table_name="model_usage_logs")
    op.drop_index(op.f("ix_model_usage_logs_created_at"), table_name="model_usage_logs")
    op.drop_table("model_usage_logs")
    op.drop_index(op.f("ix_model_usage_daily_date"), table_name="model_usage_daily")
    op.drop_table("model_usage_daily")
    op.drop_index(op.f("ix_model_instances_status"), table_name="model_instances")
    op.drop_index(op.f("ix_model_instances_api_key_id"), table_name="model_instances")
    op.drop_table("model_instances")
    op.drop_index(op.f("ix_model_health_logs_status"), table_name="model_health_logs")
    op.drop_index(op.f("ix_model_health_logs_model_id"), table_name="model_health_logs")
    op.drop_index(
        op.f("ix_model_health_logs_checked_at"), table_name="model_health_logs"
    )
    op.drop_table("model_health_logs")
    op.drop_table("cost_alerts")
    op.drop_table("circuit_breaker_states")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_vault_path"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("ab_results")
    op.drop_table("ab_groups")
    op.drop_table("ab_experiments")
    # ### end Alembic commands ###
